# Generated by Django 4.1.7 on 2023-04-06 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('campo', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(blank=True, choices=[('Jugador', 'Jugador'), ('Director tecnico', 'Director tecnico'), ('Auxiliar', 'Auxiliar')], max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.liga')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.liga'),
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('posicion', models.IntegerField()),
                ('goles_a_favor', models.IntegerField()),
                ('goles_en_contra', models.IntegerField()),
                ('diferencia_goles', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.liga')),
            ],
        ),
        migrations.CreateModel(
            name='CampoDeJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_terminacion', models.TimeField()),
                ('goles_local', models.PositiveIntegerField()),
                ('goles_visitante', models.PositiveIntegerField()),
                ('campo_juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.campodejuego')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='miliga.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='miliga.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miliga.liga')),
            ],
            options={
                'unique_together': {('fecha', 'hora_inicio', 'campo_juego')},
            },
        ),
    ]
