# Generated by Django 4.1.7 on 2023-04-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0002_alter_liga_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
