# Generated by Django 4.1.7 on 2023-04-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0004_rename_escudo_equipo_escudo_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='identificacion_img',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='jugador_img',
            field=models.ImageField(blank=True, null=True, upload_to='jugadores/'),
        ),
    ]
