# Generated by Django 4.1.7 on 2023-04-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0005_jugador_identificacion_img_jugador_jugador_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liga',
            options={'verbose_name_plural': 'Ligas'},
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='numero',
            new_name='numero_playera',
        ),
        migrations.AddField(
            model_name='equipo',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='telefono',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
