# Generated by Django 4.1.7 on 2023-04-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0006_alter_liga_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='ocupacion',
            field=models.CharField(blank=True, choices=[('Jugador', 'Jugador'), ('Director tecnico', 'Director tecnico'), ('Auxiliar', 'Auxiliar')], default='Jugador', max_length=100, null=True),
        ),
    ]
