# Generated by Django 4.1.7 on 2023-04-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0007_equipo_activo_alter_jugador_ocupacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campodejuego',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='clasificacion',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='liga',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='liga',
        ),
        migrations.DeleteModel(
            name='Liga',
        ),
    ]
