# Generated by Django 4.1.7 on 2023-04-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0008_remove_campodejuego_liga_remove_clasificacion_liga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='diferencia_goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_a_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_en_contra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='partidos_perdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Clasificacion',
        ),
    ]
