# Generated by Django 4.1.7 on 2023-04-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0009_equipo_diferencia_goles_equipo_goles_a_favor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campodejuego',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
