# Generated by Django 4.1.7 on 2023-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0010_alter_campodejuego_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='hora_terminacion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
