# Generated by Django 4.1.7 on 2023-04-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0012_jornada_partido_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='jornada',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='miliga.jornada'),
        ),
    ]
