# Generated by Django 4.1.7 on 2023-04-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0013_alter_partido_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
