# Generated by Django 4.1.7 on 2023-04-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0015_partido_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='vuelta',
            field=models.IntegerField(default=1),
        ),
    ]
