# Generated by Django 4.1.7 on 2023-04-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0017_equipo_partidos_juados'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='resultado_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
