# Generated by Django 4.1.7 on 2023-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miliga', '0020_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
